###################################################################

# Created by write_sdc on Mon Dec 14 02:07:32 2020

###################################################################
set sdc_version 1.8

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports {mem_addr_I[31]}]
set_load -pin_load 1 [get_ports {mem_addr_I[30]}]
set_load -pin_load 1 [get_ports {mem_addr_I[29]}]
set_load -pin_load 1 [get_ports {mem_addr_I[28]}]
set_load -pin_load 1 [get_ports {mem_addr_I[27]}]
set_load -pin_load 1 [get_ports {mem_addr_I[26]}]
set_load -pin_load 1 [get_ports {mem_addr_I[25]}]
set_load -pin_load 1 [get_ports {mem_addr_I[24]}]
set_load -pin_load 1 [get_ports {mem_addr_I[23]}]
set_load -pin_load 1 [get_ports {mem_addr_I[22]}]
set_load -pin_load 1 [get_ports {mem_addr_I[21]}]
set_load -pin_load 1 [get_ports {mem_addr_I[20]}]
set_load -pin_load 1 [get_ports {mem_addr_I[19]}]
set_load -pin_load 1 [get_ports {mem_addr_I[18]}]
set_load -pin_load 1 [get_ports {mem_addr_I[17]}]
set_load -pin_load 1 [get_ports {mem_addr_I[16]}]
set_load -pin_load 1 [get_ports {mem_addr_I[15]}]
set_load -pin_load 1 [get_ports {mem_addr_I[14]}]
set_load -pin_load 1 [get_ports {mem_addr_I[13]}]
set_load -pin_load 1 [get_ports {mem_addr_I[12]}]
set_load -pin_load 1 [get_ports {mem_addr_I[11]}]
set_load -pin_load 1 [get_ports {mem_addr_I[10]}]
set_load -pin_load 1 [get_ports {mem_addr_I[9]}]
set_load -pin_load 1 [get_ports {mem_addr_I[8]}]
set_load -pin_load 1 [get_ports {mem_addr_I[7]}]
set_load -pin_load 1 [get_ports {mem_addr_I[6]}]
set_load -pin_load 1 [get_ports {mem_addr_I[5]}]
set_load -pin_load 1 [get_ports {mem_addr_I[4]}]
set_load -pin_load 1 [get_ports {mem_addr_I[3]}]
set_load -pin_load 1 [get_ports {mem_addr_I[2]}]
set_load -pin_load 1 [get_ports {ctrl_signal[11]}]
set_load -pin_load 1 [get_ports {ctrl_signal[10]}]
set_load -pin_load 1 [get_ports {ctrl_signal[9]}]
set_load -pin_load 1 [get_ports {ctrl_signal[8]}]
set_load -pin_load 1 [get_ports {ctrl_signal[7]}]
set_load -pin_load 1 [get_ports {ctrl_signal[6]}]
set_load -pin_load 1 [get_ports {ctrl_signal[5]}]
set_load -pin_load 1 [get_ports {ctrl_signal[4]}]
set_load -pin_load 1 [get_ports {ctrl_signal[3]}]
set_load -pin_load 1 [get_ports {ctrl_signal[2]}]
set_load -pin_load 1 [get_ports {ctrl_signal[1]}]
set_load -pin_load 1 [get_ports {ctrl_signal[0]}]
set_load -pin_load 1 [get_ports {immediate[31]}]
set_load -pin_load 1 [get_ports {immediate[30]}]
set_load -pin_load 1 [get_ports {immediate[29]}]
set_load -pin_load 1 [get_ports {immediate[28]}]
set_load -pin_load 1 [get_ports {immediate[27]}]
set_load -pin_load 1 [get_ports {immediate[26]}]
set_load -pin_load 1 [get_ports {immediate[25]}]
set_load -pin_load 1 [get_ports {immediate[24]}]
set_load -pin_load 1 [get_ports {immediate[23]}]
set_load -pin_load 1 [get_ports {immediate[22]}]
set_load -pin_load 1 [get_ports {immediate[21]}]
set_load -pin_load 1 [get_ports {immediate[20]}]
set_load -pin_load 1 [get_ports {immediate[19]}]
set_load -pin_load 1 [get_ports {immediate[18]}]
set_load -pin_load 1 [get_ports {immediate[17]}]
set_load -pin_load 1 [get_ports {immediate[16]}]
set_load -pin_load 1 [get_ports {immediate[15]}]
set_load -pin_load 1 [get_ports {immediate[14]}]
set_load -pin_load 1 [get_ports {immediate[13]}]
set_load -pin_load 1 [get_ports {immediate[12]}]
set_load -pin_load 1 [get_ports {immediate[11]}]
set_load -pin_load 1 [get_ports {immediate[10]}]
set_load -pin_load 1 [get_ports {immediate[9]}]
set_load -pin_load 1 [get_ports {immediate[8]}]
set_load -pin_load 1 [get_ports {immediate[7]}]
set_load -pin_load 1 [get_ports {immediate[6]}]
set_load -pin_load 1 [get_ports {immediate[5]}]
set_load -pin_load 1 [get_ports {immediate[4]}]
set_load -pin_load 1 [get_ports {immediate[3]}]
set_load -pin_load 1 [get_ports {immediate[2]}]
set_load -pin_load 1 [get_ports {immediate[1]}]
set_load -pin_load 1 [get_ports {immediate[0]}]
set_max_fanout 6 [get_ports clk]
set_max_fanout 6 [get_ports rst_n]
set_max_fanout 6 [get_ports {mem_rdata_I[31]}]
set_max_fanout 6 [get_ports {mem_rdata_I[30]}]
set_max_fanout 6 [get_ports {mem_rdata_I[29]}]
set_max_fanout 6 [get_ports {mem_rdata_I[28]}]
set_max_fanout 6 [get_ports {mem_rdata_I[27]}]
set_max_fanout 6 [get_ports {mem_rdata_I[26]}]
set_max_fanout 6 [get_ports {mem_rdata_I[25]}]
set_max_fanout 6 [get_ports {mem_rdata_I[24]}]
set_max_fanout 6 [get_ports {mem_rdata_I[23]}]
set_max_fanout 6 [get_ports {mem_rdata_I[22]}]
set_max_fanout 6 [get_ports {mem_rdata_I[21]}]
set_max_fanout 6 [get_ports {mem_rdata_I[20]}]
set_max_fanout 6 [get_ports {mem_rdata_I[19]}]
set_max_fanout 6 [get_ports {mem_rdata_I[18]}]
set_max_fanout 6 [get_ports {mem_rdata_I[17]}]
set_max_fanout 6 [get_ports {mem_rdata_I[16]}]
set_max_fanout 6 [get_ports {mem_rdata_I[15]}]
set_max_fanout 6 [get_ports {mem_rdata_I[14]}]
set_max_fanout 6 [get_ports {mem_rdata_I[13]}]
set_max_fanout 6 [get_ports {mem_rdata_I[12]}]
set_max_fanout 6 [get_ports {mem_rdata_I[11]}]
set_max_fanout 6 [get_ports {mem_rdata_I[10]}]
set_max_fanout 6 [get_ports {mem_rdata_I[9]}]
set_max_fanout 6 [get_ports {mem_rdata_I[8]}]
set_max_fanout 6 [get_ports {mem_rdata_I[7]}]
set_max_fanout 6 [get_ports {mem_rdata_I[6]}]
set_max_fanout 6 [get_ports {mem_rdata_I[5]}]
set_max_fanout 6 [get_ports {mem_rdata_I[4]}]
set_max_fanout 6 [get_ports {mem_rdata_I[3]}]
set_max_fanout 6 [get_ports {mem_rdata_I[2]}]
set_max_fanout 6 [get_ports {mem_rdata_I[1]}]
set_max_fanout 6 [get_ports {mem_rdata_I[0]}]
set_max_fanout 6 [get_ports Port7]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -name CLK  -period 5  -waveform {0 2.5}
set_clock_latency 0.5  [get_clocks CLK]
set_clock_uncertainty 0.1  [get_clocks CLK]
set_input_delay -clock CLK  0.1  [get_ports rst_n]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[31]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[30]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[29]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[28]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[27]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[26]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[25]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[24]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[23]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[22]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[21]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[20]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[19]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[18]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[17]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[16]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[15]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[14]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[13]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[12]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[11]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[10]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[9]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[8]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[7]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[6]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[5]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[4]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[3]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[2]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[1]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[0]}]
set_input_delay -clock CLK  0.1  [get_ports Port7]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[31]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[30]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[29]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[28]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[27]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[26]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[25]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[24]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[23]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[22]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[21]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[20]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[19]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[18]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[17]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[16]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[15]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[14]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[13]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[12]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[11]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[10]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[9]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[8]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[7]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[6]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[5]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[4]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[3]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[2]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[11]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[10]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[9]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[8]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[7]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[6]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[5]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[4]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[3]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[2]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[1]}]
set_output_delay -clock CLK  0.1  [get_ports {ctrl_signal[0]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[31]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[30]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[29]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[28]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[27]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[26]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[25]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[24]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[23]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[22]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[21]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[20]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[19]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[18]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[17]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[16]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[15]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[14]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[13]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[12]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[11]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[10]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[9]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[8]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[7]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[6]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[5]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[4]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[3]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[2]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[1]}]
set_output_delay -clock CLK  0.1  [get_ports {immediate[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports {mem_rdata_I[31]}]
set_drive 1  [get_ports {mem_rdata_I[30]}]
set_drive 1  [get_ports {mem_rdata_I[29]}]
set_drive 1  [get_ports {mem_rdata_I[28]}]
set_drive 1  [get_ports {mem_rdata_I[27]}]
set_drive 1  [get_ports {mem_rdata_I[26]}]
set_drive 1  [get_ports {mem_rdata_I[25]}]
set_drive 1  [get_ports {mem_rdata_I[24]}]
set_drive 1  [get_ports {mem_rdata_I[23]}]
set_drive 1  [get_ports {mem_rdata_I[22]}]
set_drive 1  [get_ports {mem_rdata_I[21]}]
set_drive 1  [get_ports {mem_rdata_I[20]}]
set_drive 1  [get_ports {mem_rdata_I[19]}]
set_drive 1  [get_ports {mem_rdata_I[18]}]
set_drive 1  [get_ports {mem_rdata_I[17]}]
set_drive 1  [get_ports {mem_rdata_I[16]}]
set_drive 1  [get_ports {mem_rdata_I[15]}]
set_drive 1  [get_ports {mem_rdata_I[14]}]
set_drive 1  [get_ports {mem_rdata_I[13]}]
set_drive 1  [get_ports {mem_rdata_I[12]}]
set_drive 1  [get_ports {mem_rdata_I[11]}]
set_drive 1  [get_ports {mem_rdata_I[10]}]
set_drive 1  [get_ports {mem_rdata_I[9]}]
set_drive 1  [get_ports {mem_rdata_I[8]}]
set_drive 1  [get_ports {mem_rdata_I[7]}]
set_drive 1  [get_ports {mem_rdata_I[6]}]
set_drive 1  [get_ports {mem_rdata_I[5]}]
set_drive 1  [get_ports {mem_rdata_I[4]}]
set_drive 1  [get_ports {mem_rdata_I[3]}]
set_drive 1  [get_ports {mem_rdata_I[2]}]
set_drive 1  [get_ports {mem_rdata_I[1]}]
set_drive 1  [get_ports {mem_rdata_I[0]}]
set_drive 1  [get_ports Port7]
